// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrTOaaPx2MmHlwpGJRpWmfuN5_YcyvlA',
    appId: '1:669132795493:web:c1a9ae1b20e0cd659c208c',
    messagingSenderId: '669132795493',
    projectId: 'dg-mynotes-flutter-project-1',
    authDomain: 'dg-mynotes-flutter-project-1.firebaseapp.com',
    storageBucket: 'dg-mynotes-flutter-project-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacMT5DEpj3xLDtK0niA0pfIFGshFf12U',
    appId: '1:669132795493:android:5b7cd3680afaa5a59c208c',
    messagingSenderId: '669132795493',
    projectId: 'dg-mynotes-flutter-project-1',
    storageBucket: 'dg-mynotes-flutter-project-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX3-9LuWp-YEg6J2XdNVuljJm-cNkB_ok',
    appId: '1:669132795493:ios:66c771a9e0823d409c208c',
    messagingSenderId: '669132795493',
    projectId: 'dg-mynotes-flutter-project-1',
    storageBucket: 'dg-mynotes-flutter-project-1.appspot.com',
    iosClientId: '669132795493-ivpc9d488nmeki38aj4sdt7ih19nv60v.apps.googleusercontent.com',
    iosBundleId: 'com.whatevername.mynotes',
  );
}
